# Generated by Django 3.1.5 on 2021-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
