# Generated by Django 3.1.5 on 2021-02-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0003_car_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='car_name',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='display_picture',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MissingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(blank=True, max_length=50, null=True)),
                ('car_plate', models.CharField(max_length=50)),
                ('missing_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carops.client')),
            ],
        ),
    ]
