# Generated by Django 3.1.5 on 2021-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0005_auto_20210201_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
