# Generated by Django 3.1.5 on 2021-02-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0007_auto_20210201_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
    ]
