# Generated by Django 3.1.5 on 2021-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0009_auto_20210201_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
