# Generated by Django 3.1.5 on 2021-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carops', '0013_auto_20210201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
